---
title: "Publication"
---

## Journal Publications

-   **Chun-Hao Yang**, Hani Doss, and Baba C. Vemuri. *An Empirical Bayes Approach to Shrinkage Estimation on the Manifold of Symmetric Positive-Definite Matrices*. Journal of the American Statistical Association (2023+) Accepted.
    +   DOI: <https://doi.org/10.1080/01621459.2022.2110877>
    +   Github: [SPD-SURE](https://github.com/chun-hao/SPD-SURE)

-   **Chun-Hao Yang**, and Baba C. Vemuri. *Nested Grassmannians for Dimensionality Reduction with Applications*. Journal of Machine Learning for Biomedical Images (2022): 1--21.
    +   DOI: <https://doi.org/10.59275/j.melba.2022-234f>  
    +   Github: [NetstedGrassmann](https://github.com/chun-hao/NestedGrassmann)

-   **Chun-Hao Yang**, James V. Zidek, and Samuel W. K. Wong. *Bayesian Analysis of Accumulated Damage Models in Lumber Reliability*. Technometrics 61, no. 2 (2019): 233--245. 
    +   DOI: <https://doi.org/10.1080/00401706.2018.1512900>
    +   Github: [abc-adm](https://github.com/wongswk/abc-adm)

-   Ping-Yang Chen, Ching-Chuan Chen, **Chun-Hao Yang**, Sheng-Mao Chang, and Kuo-Jung Lee. *milr: Multiple-Instance Logistic Regression with Lasso Penalty*. R Journal 9, no. 1 (2017): 446--457. 
    +   DOI: <https://doi.org/10.32614/RJ-2017-013>
    +   Github: [milr](https://github.com/PingYangChen/milr)

## Conference Publications

- Xiran Fan, **Chun-Hao Yang**, Baba C. Vemuri. *Horospherical Decision Boundaries for Large Margin Classification in Hyperbolic Space* in Advances in Neural Information Processing Systems (NeurIPS), 2023.
    +   <https://proceedings.neurips.cc/paper_files/paper/2023/hash/24cb8b08f3cb2f59671e33faac4790e6-Abstract-Conference.html>

- Jose J. Bouza, **Chun-Hao Yang**, and Baba C. Vemuri. *Geometric Deep Learning for Unsupervised Registration of Diffusion Magnetic Resonance Images* in International Conference on Information Processing in Medical Imaging (IPMI), 2023.
    +   DOI: <https://doi.org/10.1007/978-3-031-34048-2_43>

- Xiran Fan, **Chun-Hao Yang**, and Baba C. Vemuri. *Nested Hyperbolic Spaces for Dimensionality Reduction and Hyperbolic NN Design* in Computer Vision and Machine Learning (CVPR), 2022.
    +   DOI: <https://doi.org/10.1109/CVPR52688.2022.00045>

- **Chun-Hao Yang** and Baba C. Vemuri. *Nested Grassmanns for Dimensionality Reduction with Applications to Shape Analysis* in International Conference on Information Processing in Medical Imaging (IPMI), 2021.
    +   DOI: <https://doi.org/10.1007/978-3-030-78191-0_11>

- Jose J. Bouza, **Chun-Hao Yang**, David Vaillancourt, and Baba C. Vemuri. *A Higher Order Manifold-Valued Convolutional Neural Network with Applications in Diffusion MRI Processing* in International Conference on Information Processing in Medical Imaging (IPMI), 2021.
    +   DOI: <https://doi.org/10.1007/978-3-030-78191-0_24>

- **Chun-Hao Yang** and Baba C. Vemuri. *Shrinkage Estimation on the Manifold of Symmetric Positive-Definite Matrices with Applications to Neuroimaging* in International Conference on Information Processing in Medical Imaging (IPMI), 2019.
    +   DOI: <https://doi.org/10.1007/978-3-030-20351-1_44>

- Rudrasis Chakraborty, **Chun-Hao Yang**, Xingjian Zhen, Monami Banerjee, Derek Archer, David Vaillancourt, Vikas Singh and Baba C. Vemuri. *A Statistical Recurrent Model on the Manifold of Symmetric Positive Definite Matrices* in Advances in Neural Information Processing Systems (NeurIPS), 2018.
    +   <https://papers.nips.cc/paper_files/paper/2018/hash/7070f9088e456682f0f84f815ebda761-Abstract.html>

- Rudrasis Chakraborty, **Chun-Hao Yang**, and Baba C. Vemuri, *A Mixture Model for Aggregation of Multiple Pre-trained Weak Classifiers* in 4th International Workshop on Diff-CVML: Differential Geometry in Computer Vision and Machine Learning (CVPR), 2018.
    +   DOI: <https://doi.org/10.1109/CVPRW.2018.00074>
